name: elephant_server
description: elephant server
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  async: ^2.8.2
  postgres: ^2.4.3
